# Linear Algebra Homework Assignment 1

In [1]:
import numpy as np

# Section 1: Matrix Multiplication
For each question: (a) Multiply manually showing row × column dot products, then (b) verify with NumPy using the @ operator.


**Question 1.1 - 2x2 Matrix Multiplication** <br>
Compute A × B given:

In [14]:
# (1,1): 2*4 + 3*2 = 8 + 6 = 14
# (1,2): 2*0 + 3*5 = 0 + 15 = 15
# (2,1): 1*4 + (-1)*2 = 4 - 2 = 2
# (2,2): 1*0 + (-1)*5 = 0 - 5 = -5

# Answer:

# [[14, 15],
#  [2, -5]]


matrix_a = np.array([[2, 3],
                    [1, -1]])

matrix_b = np.array([[4, 0],
                    [2, 5]])

print(matrix_a @ matrix_b)

[[14 15]
 [ 2 -5]]


**Question 1.2 — 3×3 Matrix Multiplication** <br>
Compute A × B given:

In [18]:
# Row 1

# (1,1): 1*2 + 2*0 + 0*1 = 2
# (1,2): 1*1 + 2*3 + 0*(-2) = 1 + 6 = 7
# (1,3): 1*(-1) + 2*2 + 0*4 = -1 + 4 = 3

# Row 2

# (2,1): 3*2 + (-1)*0 + 4*1 = 6 + 0 + 4 = 10
# (2,2): 3*1 + (-1)*3 + 4*(-2) = 3 - 3 - 8 = -8
# (2,3): 3*(-1) + (-1)*2 + 4*4 = -3 - 2 + 16 = 11

# Row 3

# (3,1): 0*2 + 2*0 + 1*1 = 1
# (3,2): 0*1 + 2*3 + 1*(-2) = 6 - 2 = 4
# (3,3): 0*(-1) + 2*2 + 1*4 = 4 + 4 = 8

# Answer:

# [[ 2,  7,  3],
#  [10, -8, 11],
#  [ 1,  4,  8]]


matrix_a = np.array([[1, 2, 0],
                    [3, -1, 4],
                    [0, 2, 1]])

matrix_b = np.array([[2, 1, -1],
                    [0, 3, 2],
                    [1, -2, 4]])

print(matrix_a @ matrix_b)

[[ 2  7  3]
 [10 -8 11]
 [ 1  4  8]]


**Question 1.3 — Scalar Multiplication** <br>
Given scalar k = 4 and Matrix A below, compute k × A:

In [4]:
matrix_a = np.array([[3, -2, 5],
                    [0, 1, -4],
                    [7, 2, 0]])
k = 4

print(k * matrix_a)

[[ 12  -8  20]
 [  0   4 -16]
 [ 28   8   0]]


# Section 2: Determinants
For each question: (a) Calculate the determinant manually using the formula, then (b) verify using np.linalg.det().

**Question 2.1 — Determinant of a 2×2 Matrix** <br>
Recall the formula for a 2×2 matrix:
$det(A) = (a × d) - (b × c)$   where $A = [[a, b], [c, d]]$


In [8]:
# a = (5 * 4) - (3 * 2)
# a = 20 - 6
# a = 14

a = np.array([[5, 3],
             [2, 4]])

print(round(np.linalg.det(a)))

14


**Question 2.2 — Determinant of another 2×2 Matrix**

In [22]:
# a = (-3 * -2) - (7 * 1)
# a = 6 - 7
# a = -1

a = np.array([[-3, 7],
             [1, -2]])

print(round(np.linalg.det(a)))

-1


# Section 3: Inverse of a Matrix
For each question: (a) Find the inverse manually, then (b) verify using np.linalg.inv(). Remember: only matrices with non-zero determinants have inverses. <br>

$$Formula:  A⁻¹ = (1 / det(A)) × [[d, -b], [-c, a]]$$

**Question 3.1 — Inverse of a 2×2 Matrix**

In [21]:
# A⁻¹ = (1 / det(A)) × [[d, -b], [-c, a]]
# A = (4 * 1) - (2 * 3)
# A = 4 - 6
# A = -2
# A⁻¹ = (1 / det(-2)) × [[1, -2], [-3, 4]]      -0.5 * 1, -0.5 * -2
                                            #   -0.5 * -3, -0.5 * 4
# A⁻¹ = -0.5, 1
#       1.5, -2


a = np.array([[4, 2],
             [3, 1]])

print(np.linalg.inv(a))

[[-0.5  1. ]
 [ 1.5 -2. ]]


**Question 3.2 — Inverse of another 2×2 Matrix**

In [26]:
# Matrix A:
# [[ 6, -2],
#  [-3,  1]]

# To check if A is invertible, compute the determinant:
# det(A) = (6 * 1) - (-2 * -3)

# Step-by-step:
# 6 * 1 = 6
# -2 * -3 = +6   # negative * negative = positive

# Now subtract:
# det(A) = 6 - 6 = 0

# Since the determinant is 0, the matrix is singular.
# A singular matrix has NO inverse.

# That is why np.linalg.inv(a) gives:
# LinAlgError: Singular matrix

a = np.array([[6, -2],
             [-3, 1]])

# print(np.linalg.inv(a)) Can't do because it has a determinant of zero

# Section 4: Systems of Linear Equations (Ax = b)
For each question: (a) Solve manually using substitution or elimination, then (b) verify using np.linalg.solve().

**Question 4.1 — System of 2 Equations** <br>
Solve for x and y: 

    2x + 5y = 20
    4x -  y = 10


In [33]:
# y = -10 + 4x
# y = 4x - 10
# 2x + 5(4x -10) = 20
# 2x + 20x -50 = 20
# 22x = 70
# x = 3.181818181818182
# 4(3.181818181818182) - y = 10
# 12.72727272727273 - y = 10
# y = 2.72727272727273

a = np.array([[2, 5],
             [4, -1]])

b = np.array([20, 10])

print(np.linalg.solve(a, b))

[3.18181818 2.72727273]


**Question 4.2 — System of 2 Equations** <br>
Solve for x and y:

    3x - 2y = 1
     x + 4y = 15


In [34]:
# x + 4y = 15
# x = 15 - 4y

# 3(15 - 4y) - 2y = 1
# 45 - 12y - 2y = 1
# 45 - 14y = 1
# -14y = 1 - 45
# -14y = -44
# y = 3.142857142857143 

# x = 15 - 4y
# x = 15 - 4(3.142857142857143)
# x = 15 - 12.57142857142857
# x = 2.42857142857143    

a = np.array([[3, -2],
             [1, 4]])

b = np.array([1, 15])

print(np.linalg.solve(a, b))


[2.42857143 3.14285714]


**Question 4.3 — System of 3 Equations (Challenge)** <br>
Solve for x, y, and z:

     x + 2y +  z = 8
    3x -  y + 2z = 11
    2x + 3y -  z = 7
Hint: Reduce to a 2-equation system first by eliminating one variable.


In [35]:
# x + 2y + z = 8
# 3x - y + 2z = 11
# 2x + 3y - z = 7

# Eliminate z using Eq1 and Eq2
# Multiply Eq1 by -2:
# -2x - 4y - 2z = -16
# Add to Eq2:
# (3x - y + 2z) + (-2x - 4y - 2z) = 11 - 16
# x - 5y = -5

# Eliminate z using Eq1 and Eq3
# Multiply Eq1 by 1:
# x + 2y + z = 8
# Add to Eq3:
# (2x + 3y - z) + (x + 2y + z) = 7 + 8
# 3x + 5y = 15

# Now we have a 2‑equation system:
# x - 5y = -5
# 3x + 5y = 15

# Add the two equations:
# (x - 5y) + (3x + 5y) = -5 + 15
# 4x = 10
# x = 2.5

# Plug x into x - 5y = -5
# 2.5 - 5y = -5
# -5y = -7.5
# y = 1.5

# Plug x and y into Eq1:
# x + 2y + z = 8
# 2.5 + 3 + z = 8
# 5.5 + z = 8
# z = 2.5

# Final answers:
# x = 2.5
# y = 1.5
# z = 2.5

a = np.array([[1, 2, 1],
             [3, -1, 2],
             [2, 3, -1]])

b = np.array([8, 11, 7])

print(np.linalg.solve(a, b))

[2.5 1.5 2.5]
