In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
arr = np.zeros((3, 3))
arr[1, 1] = 9

print(arr)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [5]:
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [14]:
arr = np.arange(1, 13)
grid = arr.reshape(3, 4)
print(grid)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
arr = np.ones((4, 3))
print('Shape:', arr.shape)
print('Rows:', arr.shape[0])
print('Total elements:', arr.size)

Shape: (4, 3)
Rows: 4
Total elements: 12


In [22]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print('Sum:', a + b)
print('Product:', np.dot(a, b))

Sum: [11 22 33]
Product: 140


In [23]:
celsius = np.array([0, 20, 37, 100])
fahrenheit = celsius * 9/5 + 32
print(fahrenheit)

[ 32.   68.   98.6 212. ]


In [28]:
arr = np.array([4, 8, 15, 16, 23, 42])
print('Sum:', np.sum(arr))
print('Mean:', np.mean(arr))
print('Min:', np.min(arr))
print('Max:', np.max(arr))

Sum: 108
Mean: 18.0
Min: 4
Max: 42
