In [15]:
import numpy as np
import random

In [2]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
arr = np.zeros((3, 3))
arr[1, 1] = 9

print(arr)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [5]:
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [14]:
arr = np.arange(1, 13)
grid = arr.reshape(3, 4)
print(grid)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
arr = np.ones((4, 3))
print('Shape:', arr.shape)
print('Rows:', arr.shape[0])
print('Total elements:', arr.size)

Shape: (4, 3)
Rows: 4
Total elements: 12


In [22]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print('Sum:', a + b)
print('Product:', np.dot(a, b))

Sum: [11 22 33]
Product: 140


In [23]:
celsius = np.array([0, 20, 37, 100])
fahrenheit = celsius * 9/5 + 32
print(fahrenheit)

[ 32.   68.   98.6 212. ]


In [28]:
arr = np.array([4, 8, 15, 16, 23, 42])
print('Sum:', np.sum(arr))
print('Mean:', np.mean(arr))
print('Min:', np.min(arr))
print('Max:', np.max(arr))

Sum: 108
Mean: 18.0
Min: 4
Max: 42


In [6]:
arr = np.array([5, 10, 15, 20, 25, 30])
print('First:', arr[0])
print('Last:', arr[-1])
print('Middle slice', arr[2:5])

First: 5
Last: 30
Middle slice [15 20 25]


In [14]:
arr = np.arange(1, 17).reshape(4, 4)
print('Second row:', arr[1])
print('Third column:', arr[:,2])

Second row: [5 6 7 8]
Third column: [ 3  7 11 15]


In [18]:
dice_rolls = np.random.randint(1, 7, size=6)
print('Dice rolls:', dice_rolls)

Dice rolls: [4 5 2 6 6 2]


In [23]:
random_grid = np.random.rand(3, 3)
print('Grid:', random_grid)
print('Average:', np.mean(random_grid))

Grid: [[0.78386502 0.50127758 0.73699143]
 [0.87818576 0.72564692 0.92833867]
 [0.6200322  0.5738766  0.359005  ]]
Average: 0.6785799093570971


In [25]:
arr = np.array([3, 7, 2, 9, 4, 11, 6])
big_numbers = arr[arr > 5]
print('Numbers > 5:', big_numbers)

Numbers > 5: [ 7  9 11  6]


In [26]:
arr = np.array([42, 7, 19, 3, 88, 55, 1])
sorted_arr = np.sort(arr)
position = np.where(sorted_arr == 42)
print('Sorted:', sorted_arr)
print('42 is at index:', position)

Sorted: [ 1  3  7 19 42 55 88]
42 is at index: (array([4]),)


In [29]:
marks = np.array([72, 85, 60, 91, 55, 78, 88, 66])

average = np.mean(marks)

print('Average:', average)
print('Highest:', np.max(marks))
print('Lowest:', np.min(marks))

passed = marks[marks >= 60]
print('Student passed:', passed.size)

above_avg = marks[marks >= average]
print('Above average marks:', above_avg.size)

Average: 74.375
Highest: 91
Lowest: 55
Student passed: 7
Above average marks: 4
