# General Numpy Revisions

In [1]:
import numpy as np

1. Create a 1D array of numbers from 0 to 50 in steps of 5, then a 3×3 array filled with zeros.

In [11]:
arr = np.arange(0, 51, 5)
print(arr)

arr = np.zeros((3,3))
print(arr)

[ 0  5 10 15 20 25 30 35 40 45 50]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2. Generate 6 evenly spaced values between 0 and 1 using np.linspace(), then create a 2D array of random integers between 10 and 50 with shape (4, 3).

In [15]:
arr = np.linspace(0, 1, 6)
print(arr)

arr = np.random.randint(10, 51, size = (4, 3))
print(arr)

[0.  0.2 0.4 0.6 0.8 1. ]
[[41 17 16]
 [29 13 27]
 [44 48 36]
 [28 31 49]]


3. Given a 1D array of 10 values, print the last 3 elements.

In [20]:
arr = np.arange(10, 110, 10)
print(arr[-3:])

[ 80  90 100]


4. Given an array of exam scores, calculate the mean, min, max, and standard deviation. Then find the index of the highest score.

In [22]:
scores = np.array([72, 88, 95, 61, 79, 100, 83])

print(np.mean(scores))
print(np.min(scores))
print(np.max(scores))
print(np.std(scores))
print(np.argmax(scores))

82.57142857142857
61
100
12.408029000347693
5


5. From an array of salaries, use boolean indexing to find all values above 4000. Then use np.where() to replace values below 3000 with 0.

In [33]:
sal = np.array([2500, 4000, 3800, 3200, 4000, 3500, 3700, 5100, 1600])

condition = sal > 4000

print(sal[condition])

condition2 = sal < 3000

filtered = np.where(condition2, 0, sal)

print(filtered)

[5100]
[   0 4000 3800 3200 4000 3500 3700 5100    0]


6. Multiply two 3×3 matrices together using the @ operator, then verify the result using np.dot().

In [13]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.eye(3)

print(A @ B)

print(np.dot(A, B))

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


7. Solve the system of equations: 2x + y = 5 and 5x + 3y = 13 using np.linalg.solve().

In [15]:
A = np.array([[2, 1],
             [5, 3]])

B = np.array([5, 13])

print(np.linalg.solve(A, B))

[2. 1.]
