# HW 1D Arrays

## Overview
This homework covers the basics of one‑dimensional arrays, including how they are created, stored, and used in programs.

## Key Concepts
- What a 1D array is  
- How to declare and initialize an array  
- How to access elements  
- How indexing works  
- Common operations (traversing, updating values)

## Notes
- Array indices start at 0  
- Arrays store elements of the same data type  
- Accessing an index outside the array’s bounds causes errors

## Submission
- Submit your completed work as instructed by your teacher  
- Ensure your formatting is clear and organized

## Level 1 - Creating Arrays <br>



**Task 1** Create a Numpy array containing the numbers 1 to 10 using two different methods.

In [1]:
import numpy as np # Import

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr2 = np.arange(1, 11)

print(arr)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


**Task 2** Create an array of 6 evenly spaced numbers between 0, 1 (inclusive of both ends).

In [22]:
arr = np.linspace(0, 1, 6)

print(arr)

[0.  0.2 0.4 0.6 0.8 1. ]


**Task 3** Create an array of 5 zeros, then create an array of 5 ones. Then print the data type of each.

In [23]:
arr = np.zeros(5)
arr2 = np.ones(5)

print( arr, arr.dtype)
print( arr2, arr2.dtype)

[0. 0. 0. 0. 0.] float64
[1. 1. 1. 1. 1.] float64


Given an Array with values ([0,2,5,3,7,18,20,21,11,14]). <br>
1. Find the maximum number in this arrays?
2. Find the index for the maximum number in this array?
3. Added the maximum number in this array to the value that follows this number in the array?

In [9]:
arr = np.array([0,2,5,3,43,7,18,20,21,11,14])
print(np.max(arr))
print(np.argmax(arr))
m_index = np.argmax(arr) # m_index equals to the index of the max number which is 43
n_index = m_index + 1 # n_index equals to the m_index + 1 which is 7
sum = arr[m_index] + arr[n_index] # sum equals to addition of both m and n index
print(sum) # print sum which gives 50

43
4
50


**General Practice**

Print all values that are even numbers only. <br>
Print all values between 100 and 600 (greater than 100 AND less than 600).

In [3]:
arr = np.array([45, 3, 78, 12, 56, 89, 23, 67, 4, 100, 34, 91, 7, 55, 82, 19, 63, 48, 11, 74, 27, 95, 6, 61, 38, 84, 17, 72, 50, 9, 66, 43, 88, 25, 70, 14, 57, 31, 99, 2, 83, 47, 16, 69, 36, 92, 8, 53, 77, 21, 64, 40, 86, 13, 58, 29, 97, 5, 71, 44, 18, 76, 33, 90, 22, 68, 41, 85, 10, 54, 79, 26, 93, 15, 60, 37, 80, 49, 1, 73, 28, 96, 42, 65, 20, 87, 32, 75, 46, 59, 94, 24, 62, 39, 81, 52, 35, 98, 30, 76, 101, 234, 567, 890, 123, 456, 789, 321, 654, 987, 112, 445, 778, 224, 557, 880, 333, 666, 999, 111, 444, 777, 222, 555, 888, 143, 476, 809, 132, 465, 798, 311, 644, 977, 255, 588, 166, 499, 177, 510, 843, 276, 609, 342, 675, 208, 541, 874, 307, 640, 973, 406, 739, 172, 505, 838, 271, 604, 937, 370, 703, 136, 469, 802, 235, 568, 901, 134, 467, 800, 233, 566, 899, 402, 735, 168, 501, 834, 267, 600])

print(arr.size)
print(arr.dtype)
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(arr[4:12])
print(arr[::3])
print(arr[::-1])
print(np.argmax(arr))
print(np.argmin(arr))

m_index = np.argmin(arr)
n_index = m_index - 1
sub = arr[m_index] - arr[n_index]
print(sub)

condition1 = arr > 500

print(arr[condition1])
print(np.sort(arr[condition1]))

condition2 = arr % 2 == 0

print(arr[condition2])

between = (arr > 100) & (arr < 600)

print(arr[between])

180
int64
46688
1
999
294.42558304369084
[ 56  89  23  67   4 100  34  91]
[ 45  12  23 100   7  19  11  95  38  72  66  25  57   2  16  92  77  40
  58   5  18  90  41  54  93  37   1  96  20  75  94  39  35  76 567 456
 654 445 557 666 444 555 476 465 644 588 177 276 675 874 973 172 271 370
 469 568 467 566 735 834]
[600 267 834 501 168 735 402 899 566 233 800 467 134 901 568 235 802 469
 136 703 370 937 604 271 838 505 172 739 406 973 640 307 874 541 208 675
 342 609 276 843 510 177 499 166 588 255 977 644 311 798 465 132 809 476
 143 888 555 222 777 444 111 999 666 333 880 557 224 778 445 112 987 654
 321 789 456 123 890 567 234 101  76  30  98  35  52  81  39  62  24  94
  59  46  75  32  87  20  65  42  96  28  73   1  49  80  37  60  15  93
  26  79  54  10  85  41  68  22  90  33  76  18  44  71   5  97  29  58
  13  86  40  64  21  77  53   8  92  36  69  16  47  83   2  99  31  57
  14  70  25  88  43  66   9  50  72  17  84  38  61   6  95  27  74  11
  48  63  19  82  55   