# HW 1D Arrays

## Overview
This homework covers the basics of one‑dimensional arrays, including how they are created, stored, and used in programs.

## Key Concepts
- What a 1D array is  
- How to declare and initialize an array  
- How to access elements  
- How indexing works  
- Common operations (traversing, updating values)

## Notes
- Array indices start at 0  
- Arrays store elements of the same data type  
- Accessing an index outside the array’s bounds causes errors

## Submission
- Submit your completed work as instructed by your teacher  
- Ensure your formatting is clear and organized

## Level 1 - Creating Arrays <br>



**Task 1** Create a Numpy array containing the numbers 1 to 10 using two different methods.

In [1]:
import numpy as np # Import

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr2 = np.arange(1, 11)

print(arr)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


**Task 2** Create an array of 6 evenly spaced numbers between 0, 1 (inclusive of both ends).

In [22]:
arr = np.linspace(0, 1, 6)

print(arr)

[0.  0.2 0.4 0.6 0.8 1. ]


**Task 3** Create an array of 5 zeros, then create an array of 5 ones. Then print the data type of each.

In [23]:
arr = np.zeros(5)
arr2 = np.ones(5)

print( arr, arr.dtype)
print( arr2, arr2.dtype)

[0. 0. 0. 0. 0.] float64
[1. 1. 1. 1. 1.] float64


Given an Array with values ([0,2,5,3,7,18,20,21,11,14]). <br>
1. Find the maximum number in this arrays?
2. Find the index for the maximum number in this array?
3. Added the maximum number in this array to the value that follows this number in the array?

In [9]:
arr = np.array([0,2,5,3,43,7,18,20,21,11,14])
print(np.max(arr))
print(np.argmax(arr))
m_index = np.argmax(arr) # m_index equals to the index of the max number which is 43
n_index = m_index + 1 # n_index equals to the m_index + 1 which is 7
sum = arr[m_index] + arr[n_index] # sum equals to addition of both m and n index
print(sum) # print sum which gives 50

43
4
50
