# HW 2D Arrays

In [16]:
import numpy as np
import matplotlib.pyplot as plt

In [16]:
arr = np.array([[ 10, 20, 30, 40],
                [ 50, 60, 70, 80],
                [ 90, 100, 110, 120],
                [130, 140, 150, 160]])

## Row Slicing

1. Extract the third row from the array above

In [5]:
print(arr[2, :])

[ 90 100 110 120]


2. Extract the second and third row

In [7]:
print(arr[1:3, :])

[[ 50  60  70  80]
 [ 90 100 110 120]]


3. Use two different methods to extract the last row

In [9]:
print(arr[-1, :])
print(arr[3, :])

[130 140 150 160]
[130 140 150 160]


4. Reverse the rows

In [31]:
print(arr[::-1]) # Reverse the rows
print(arr[::-1, :]) # Same thing but usually more accurate

[[130 140 150 160]
 [ 90 100 110 120]
 [ 50  60  70  80]
 [ 10  20  30  40]]
[[130 140 150 160]
 [ 90 100 110 120]
 [ 50  60  70  80]
 [ 10  20  30  40]]


## Column Slicing

In [18]:
arr = np.array([[ 10, 20, 30, 40],
                [ 50, 60, 70, 80],
                [ 90, 100, 110, 120],
                [130, 140, 150, 160]])

1. Extract the first column

In [23]:
print(arr[:, 0])

[ 10  50  90 130]


2. Extract the second and third column

In [24]:
print(arr[:, 1:3])

[[ 20  30]
 [ 60  70]
 [100 110]
 [140 150]]


3. Extract the last column

In [25]:
print(arr[:, -1])

[ 40  80 120 160]


4. Reverse the columns

In [30]:
print(arr[:, ::-1]) # Reverse the columns

[[ 40  30  20  10]
 [ 80  70  60  50]
 [120 110 100  90]
 [160 150 140 130]]
