# Numpy Arrays 2D

In [1]:
import numpy as np

### What is a 2D Array

A 2D Array is essentially a list of lists but stored as a continuous block of memory with shape (rows, columns)

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.size)
print(arr.dtype)

9
int64


### Indexing

In [21]:
arr = np.array([[4, 2, 7], [6, 1, 3], [8, 9, 5]])

print(arr[1, 2]) # 1 is the index of the second list and 2 is the index of the 3rd element of that list (3)
print(arr[-1, -1]) # -1 for the last list and -1 for the last element of that list (5)

3
5


### Slicing Syntax

The full syntax for slicing in 2D arrays is arr[row_start : row_stop : row_step, col_start : col_stop : col_step]. Stop is always excluded.

In [32]:
arr = np.array([[ 10, 20, 30, 40],
              [ 50, 60, 70, 80],
              [ 90, 100, 110, 120],
              [130, 140, 150, 160]])

print(arr[1, :]) # Single row slicing
print(arr[:, 2]) # Single column slicing
print(arr[1:3, :]) # Multiple row slicing
print(arr[:, 1:3]) # Multiple column slicing
print(arr[1:3, 1:3]) # Submatrix slicing

[50 60 70 80]
[ 30  70 110 150]
[[ 50  60  70  80]
 [ 90 100 110 120]]
[[ 20  30]
 [ 60  70]
 [100 110]
 [140 150]]
[[ 60  70]
 [100 110]]


# Adding and subtracting matrices

- When it come to adding and subtracting matrices, both matrices should have the same size (order) rowxcols.

- When subtracting matrices, the order of the two matrices matters, because the order determines the outcome.

In [8]:
matrix_a = np.array([[10, 2, 5],
                    [-6, 4, -1],
                    [-2, 7, 3]])

matrix_b = np.array([[-1, 3, 2],
                    [12, 0, 9],
                    [-7, -2, 6]])

print(matrix_a + matrix_b)
print(matrix_a - matrix_b)

[[ 9  5  7]
 [ 6  4  8]
 [-9  5  9]]
[[ 11  -1   3]
 [-18   4 -10]
 [  5   9  -3]]


# Multiplication of matrices 

1. Multiplying a matrix with a scalar factor (Simple)
2. Multiply 2 matrix (Follow the rules)

### Multiplication by a scalar factor

In [2]:
matrix_a = np.array([[10, 2, 5],
                    [-6, 4, -1],
                    [-2, 7, 3]])
scalar = 10
print(scalar * matrix_a)


[[100  20  50]
 [-60  40 -10]
 [-20  70  30]]


### Multiplying by 2 matrices

In [8]:
matrix_a = np.array([[-2, 1],
                     [0, 3]])

matrix_b = np.array([[3, 4],
                     [0, -1]])

print(matrix_a @ matrix_b)
print(np.dot(matrix_a, matrix_b))
print(matrix_a * matrix_b)

[[-6 -9]
 [ 0 -3]]
[[-6 -9]
 [ 0 -3]]
[[-6  4]
 [ 0 -3]]
