# Numpy Arrays 1D
### What are Numpy Arrays
A Numpy Array is a grid of values all of the same type stored in a continuous block of memory. A 1D array is the simplest form - is just a single row of values like a list but far more powerful.

In [3]:
import numpy as np # Import section

In [70]:
arr = np.array([10, 20, 30, 40, 50])

print(arr)

print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


### Creating arrays

---
There are several ways to create a 1D array depending on what you need <br>
**from a Python list**

In [1]:
a = ([1,2,3,4,5])

**Range of values** -np.arange() <br>

- Start is the starting value 
- End is the ending value
- Step is the difference between each values in the array


In [71]:
arr1 = np.arange(5)
arr2 = np.arange(1, 11) # (start and end)
arr3 = np.arange(0, 11, 3) # (start, end, step)
arr4 = np.arange(10, 0, -1)
print(arr4)

[10  9  8  7  6  5  4  3  2  1]


**Evenly spaced values** <br>

To space an array evenly across numbers, for example if you are given an array from 1 to 100. <br>
When you use linspace, the array will be divided into 10s.

In [72]:
arr = np.linspace(0, 100, 11)
arr2 = np.linspace(0, 1, 10)

print(arr2)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


**Zeros and ones**

In [73]:
ones = np.ones(10)

zeros = np.zeros(10)

print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Random values**

In [25]:
arr = np.random.rand(100) # 100 is the size of the float array (range: 0-1 cannot change)
arr2 = np.random.randint(1, 100, size = 5) # 5 is the size of the array (range: 1-100 can change)

print(arr2)

[72  8 80 53 23]


### Array properties

In [73]:
a = np.array([10, 20, 30, 40.3, 50, 60])

print(a.size) # Checks the number of elements in an array
print(a.dtype) # Checks the datatype of the elements in an array
print(a.ndim) # Checks the number of dimentions in an array
print(a.shape) # Number of elements in a dimention

6
float64
1
(6,)


### Indexing
Accessing individual elements work just like Python lists.

In [5]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0]) # First element 10
arr[1] # Second element 20
arr[-1] # Always prints the last element 50
arr[-2] # 2nd last element 40

10


np.int64(40)

### Modifying elements

In [8]:
arr[0] = 290
arr[-2] = 400
print(arr)

[290  20  30 400  50]


### Slicing

Slicing lets you extract a portion of an array. The syntax is [Start: Stop: Step] where stop is excluded

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[1: 4]) # Index 1 going up but not including index 4
print(arr[0: 3]) # First 3 elements
print(arr[:3]) # Same, default start is 0
print(arr[1:]) # From index 1 to end (index 4)
print(arr[:]) # Every single element from start to end
print(arr[0:10:2]) # Step skips every 2
print(arr[::2]) # Same concept

[2 3 4]
[1 2 3]
[1 2 3]
[ 2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[1 3 5 7 9]


# Basic operators

---

### Scalar operator

With the scalar operations. Each elements in the array is independently effected by the scalar factor in the example below.

In [36]:
arr = np.array([1, 2, 3, 4, 5])

print(5 + arr) # Addition
print(5 ** arr) # Power
print(5 * arr) # Multiplication
print(5 / arr) # Division
print(5 // arr) # Floor
print(5 % arr) # Modulus
print(5 - arr) # Subtraction

[ 6  7  8  9 10]
[   5   25  125  625 3125]
[ 5 10 15 20 25]
[5.         2.5        1.66666667 1.25       1.        ]
[5 2 1 1 1]
[0 1 2 1 0]
[4 3 2 1 0]
