# Numpy Arrays 2D

In [1]:
import numpy as np

### What is a 2D Array

A 2D Array is essentially a list of lists but stored as a continuous block of memory with shape (rows, columns)

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.size)
print(arr.dtype)

9
int64


### Indexing

In [21]:
arr = np.array([[4, 2, 7], [6, 1, 3], [8, 9, 5]])

print(arr[1, 2]) # 1 is the index of the second list and 2 is the index of the 3rd element of that list (3)
print(arr[-1, -1]) # -1 for the last list and -1 for the last element of that list (5)

3
5


### Slicing Syntax

The full syntax for slicing in 2D arrays is arr[row_start : row_stop : row_step, col_start : col_stop : col_step]. Stop is always excluded.

In [32]:
arr = np.array([[ 10, 20, 30, 40],
              [ 50, 60, 70, 80],
              [ 90, 100, 110, 120],
              [130, 140, 150, 160]])

print(arr[1, :]) # Single row slicing
print(arr[:, 2]) # Single column slicing
print(arr[1:3, :]) # Multiple row slicing
print(arr[:, 1:3]) # Multiple column slicing
print(arr[1:3, 1:3]) # Submatrix slicing

[50 60 70 80]
[ 30  70 110 150]
[[ 50  60  70  80]
 [ 90 100 110 120]]
[[ 20  30]
 [ 60  70]
 [100 110]
 [140 150]]
[[ 60  70]
 [100 110]]
