# Numpy Arrays 1D
### What are Numpy Arrays
A Numpy Array is a grid of values all of the same type stored in a continuous block of memory. A 1D array is the simplest form - is just a single row of values like a list but far more powerful.

In [ ]:
import numpy as np #Import section

In [70]:
arr = np.array([10, 20, 30, 40, 50])

print(arr)

print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


### Creating arrays

---
There are several ways to create a 1D array depending on what you need <br>
**from a Python list**

In [68]:
a = ([1,2,3,4,5])

**Range of values** -np.arange() <br>

- Start is the starting value 
- End is the ending value
- Step is the difference between each values in the array


In [71]:
arr1 = np.arange(5)
arr2 = np.arange(1, 11) #(start and end)
arr3 = np.arange(0, 11, 3) #(start, end, step)
arr4 = np.arange(10, 0, -1)
print(arr4)

[10  9  8  7  6  5  4  3  2  1]


**Evenly spaced values** <br>

To space an array evenly across numbers, for example if you are given an array from 1 to 100. <br>
When you use linspace, the array will be divided into 10s.

In [72]:
arr = np.linspace(0, 100, 11)
arr2 = np.linspace(0,1, 10)

print(arr2)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


**Zeros and ones**

In [73]:
ones = np.ones(10)

zeros = np.zeros(10)

print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
