# LINEAR ALGEBRA

In [2]:
import numpy as np

## Adding and subtracting matrices

- When it come to adding and subtracting matrices, both matrices should have the same size (order) rowxcols.

- When subtracting matrices, the order of the two matrices matters, because the order determines the outcome.

In [2]:
matrix_a = np.array([[10, 2, 5],
                    [-6, 4, -1],
                    [-2, 7, 3]])

matrix_b = np.array([[-1, 3, 2],
                    [12, 0, 9],
                    [-7, -2, 6]])

print(matrix_a + matrix_b)
print(matrix_a - matrix_b)

[[ 9  5  7]
 [ 6  4  8]
 [-9  5  9]]
[[ 11  -1   3]
 [-18   4 -10]
 [  5   9  -3]]


# Multiplication of matrices 

1. Multiplying a matrix with a scalar factor (Simple)
2. Multiply 2 matrix (Follow the rules)

### Multiplication by a scalar factor

In [3]:
matrix_a = np.array([[10, 2, 5],
                    [-6, 4, -1],
                    [-2, 7, 3]])
scalar = 10
print(scalar * matrix_a)

[[100  20  50]
 [-60  40 -10]
 [-20  70  30]]


### Multiplying by 2 matrices

In [4]:
matrix_a = np.array([[-2, 1],
                     [0, 3]])

matrix_b = np.array([[3, 4],
                     [0, -1]])

print(matrix_a @ matrix_b)
print(np.dot(matrix_a, matrix_b))
print(matrix_a * matrix_b)

[[-6 -9]
 [ 0 -3]]
[[-6 -9]
 [ 0 -3]]
[[-6  4]
 [ 0 -3]]


In [5]:
matrix_a = np.array([[3, 4],
                    [-1, 0]])

matrix_b = np.array([[-1, 0],
                    [0, 1]])

print(matrix_a @ matrix_b)

[[-3  4]
 [ 1  0]]


In [6]:
matrix_a = np.array([[4, 1, 3, 6],
                    [3, 1, 7, -1],
                    [-2, 4, 5, 0],
                    [6, -3, 0, 1]])

matrix_b = np.array([[-2, -4, 10, 1],
                    [0, 7, -5, -1],
                    [-1, 6, 0, 0],
                    [0, -5, 0, 2]])

print(matrix_a @ matrix_b)

[[-11 -21  35  15]
 [-13  42  25   0]
 [ -1  66 -40  -6]
 [-12 -50  75  11]]


# Determinant of a 2x2 matrix

$$ A = \begin{pmatrix}a&b\\c&d \end{pmatrix} $$

### Formula

$$\det(A) = ad-bc$$

In [7]:
matrix_a = np.array([[-10, 3],
                    [-6, 2]])

print(np.linalg.det(matrix_a))
print(round(np.linalg.det(matrix_a))) # Rounded version

-1.999999999999998
-2


# Inverse of a matrix

$$ A = \begin{pmatrix}-3&-4\\2&1 \end{pmatrix} $$

### Steps

- Swap the major diagonal (-3, 1)
- Give the minor diagonal opposite signs (-4, 2)

### Formula

$$ A^{-1} = \frac{1}{detA} \times \text{Adj} $$

In [8]:
matrix_a = np.array([[-3, -4],
                    [2, 1]])

print(np.linalg.inv(matrix_a))

[[ 0.2  0.8]
 [-0.4 -0.6]]


## Solving linear systems

### What is Ax = b?

- A linear system is a set of equations where each unknown appears only to the first power. In matrix form:
- A is a matrix of coefficients, x is the vector of unknowns, b is the vector of constants. Solving means:
find x such that when A acts on it, you get b.

### Single linear equation

A single linear equation is just $ax = b$, simply solve as $x = \frac{b}{a}$. <br>
Numpy has no special function for this but you can still frame it as one by one system if you want consistency.

In [4]:
# Method 1 - Plain division
a = 5
b = 10
x = b/a
print(x)

# Method 2 - Using linalg.solve
A = np.array([[5]])
B = np.array([[10]])
X = np.linalg.solve(A, B)
print(X)

2.0
[[2.]]


### System of 2 equations

In [7]:
# 3x + 2y = 17
# x + y = 7

A = np.array([[3, 2],
             [1, 1]])

B = np.array([17, 7])

X = np.linalg.solve(A, B)

print(X)

a = np.array([[2, 3],
             [1, 2]])

b = np.array([16, 10])

x = np.linalg.solve(a, b)

print(x)

[3. 4.]
[2. 4.]


### System of 3 equations

In [8]:
# 2x + y - z = 3
# x + 3y + 2z = 13
# x + y + 4z = 12

A = np.array([[2, 1, -1],
             [1, 3, 2],
             [1, 1, 4]])

B = np.array([3, 13, 12])

X = np.linalg.solve(A, B)

print(X)

[1.25 2.55 2.05]
